version: '3'

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf

  app:
    build: .
    environment:
      - DB=MongoDB
    depends_on:
      - db
    volumes:
      - ./uwsgi.ini:/var/www/uwsgi.ini
      - ./app:/var/www/app

  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  #db:
  #  image: mariadb
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=root
  #db:
  #  image: redis
